apiVersion: v1
kind: Service
metadata:
  name: hello-world
  labels: { app: hello-world }
spec:
  type: NodePort
  selector: { app: hello-world }
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30081